In [1]:
import pandas as pd
from scipy.spatial.distance import pdist, cdist
import numpy as np
import math
import datetime as dt
from datetime import timedelta
import itertools
from collections import defaultdict
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "../tests")))

In [2]:
# sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..")))
import filters
import daphmeIO as loader
import constants as constants
import stop_detection_modified as SD

In [3]:
path = '../data/sample4/'

traj_cols = {'user_id':'user_id',
             'latitude':'dev_lat',
             'longitude':'dev_lon',
             'datetime':'local_datetime'}

df = loader.from_file(path, traj_cols=traj_cols, format='csv')

In [4]:
df = filters.to_projection(df, latitude='dev_lat', longitude='dev_lon')

In [5]:
df['timestamp'] = df['local_datetime'].astype('int64') // 10**9

In [6]:
df

,user_id,dev_lat,dev_lon,local_datetime,x,y,timestamp
0,wizardly_joliot,38.321711,-36.667334,2024-01-01 14:29:00,-4.081789e+06,4.624973e+06,1704119340
1,wizardly_joliot,38.321676,-36.667365,2024-01-01 14:35:00,-4.081792e+06,4.624968e+06,1704119700
2,wonderful_swirles,38.321017,-36.667869,2024-01-01 15:06:00,-4.081849e+06,4.624874e+06,1704121560
3,youthful_galileo,38.321625,-36.666612,2024-01-01 08:47:00,-4.081709e+06,4.624961e+06,1704098820
4,youthful_galileo,38.321681,-36.666841,2024-01-01 09:59:00,-4.081734e+06,4.624969e+06,1704103140
...,...,...,...,...,...,...,...
25830,angry_spence,38.320399,-36.667438,2024-01-15 07:23:00,-4.081801e+06,4.624787e+06,1705303380
25831,angry_spence,38.320413,-36.667469,2024-01-15 07:29:00,-4.081804e+06,4.624789e+06,1705303740
25832,angry_spence,38.320384,-36.667455,2024-01-15 07:33:00,-4.081802e+06,4.624785e+06,1705303980
25833,angry_spence,38.320349,-36.667473,2024-01-15 07:39:00,-4.081804e+06,4.624780e+06,1705304340
25834,angry_spence,38.320947,-36.667530,2024-01-15 07:50:00,-4.081811e+06,4.624865e+06,1705305000

In [7]:
sample_user_df = df[df['user_id'] == "youthful_galileo"]

In [8]:
time_thresh = 10
dist_thresh = 5
min_pts = 3

In [9]:
SD.temporal_dbscan(sample_user_df, time_thresh, dist_thresh, min_pts, traj_cols=traj_cols)

Time differences (seconds):
[[      0    4320    5040 ... 1192080 1194780 1196400]
 [   4320       0     720 ... 1187760 1190460 1192080]
 [   5040     720       0 ... 1187040 1189740 1191360]
 ...
 [1192080 1187760 1187040 ...       0    2700    4320]
 [1194780 1190460 1189740 ...    2700       0    1620]
 [1196400 1192080 1191360 ...    4320    1620       0]]
Time pairs (indices): (array([  2,   8,   8,   9,  16,  16,  16,  17,  17,  18,  20,  22,  25,
        25,  25,  26,  26,  27,  29,  36,  36,  37,  40,  42,  42,  43,
        43,  43,  44,  44,  45,  45,  46,  49,  51,  53,  56,  57,  58,
        59,  62,  64,  66,  66,  67,  69,  70,  70,  71,  72,  73,  75,
        75,  76,  81,  83,  83,  84,  85,  86,  86,  86,  87,  87,  88,
        92,  93,  98, 105, 107, 110, 111, 113, 117, 117, 118, 121, 121,
       122, 124, 127, 131, 133, 136, 143, 144, 144, 145, 145, 146, 147,
       147, 147, 148, 148, 149, 151, 151, 152, 152, 153, 155, 157, 157,
       158, 160, 170, 170, 171, 172, 173, 175, 177, 178, 180, 181, 181,
       182, 182, 183, 186, 188, 190, 191, 194, 196, 199, 201, 202, 203,
       204, 207, 210, 213, 216, 217, 218, 218, 219, 222, 225, 226, 227,
       230, 231, 233, 234, 235, 240, 241, 241, 242, 242, 243, 245, 247,
       247, 248, 250, 255, 256, 257, 259, 261, 263, 266, 267, 268, 269,
       272, 272, 273, 274, 281, 285, 289, 291, 292, 294, 300, 300, 301,
       305, 306, 310, 310, 311, 313, 315, 317, 321, 324, 327, 331, 334,
       341, 344, 345, 346, 348, 350, 352, 352, 353, 358, 359, 359, 360,
       360, 360, 360, 361, 361, 361, 362, 362, 363, 368, 368, 369, 372,
       373, 376, 379, 381, 384, 386, 394, 396, 398, 398, 399, 404, 404,
       405, 417, 419, 419, 420, 424, 425, 426, 428, 428, 429, 435, 438,
       442, 444, 445, 447, 448, 453, 454, 457, 457, 457, 458, 458, 459,
       461, 461, 462, 466, 467, 468, 468, 469, 474, 474, 475, 475, 476,
       477, 482, 482, 483, 486, 486, 487, 487, 488, 498, 501, 505, 507,
       508, 512, 516, 520, 523, 525, 526, 528, 531, 531, 532, 534, 537,
       539, 539, 540, 542, 544, 544, 545, 547, 547, 548, 551, 555, 557,
       558, 559, 559, 560, 562, 563, 564, 565, 566, 568, 570, 570, 571,
       571, 572, 574, 577, 580, 580, 581, 585, 585, 586, 588, 591, 597,
       600, 600, 601, 601, 602, 605, 607, 607, 608]), array([  3,   9,  10,  10,  17,  18,  19,  18,  19,  19,  21,  23,  26,
        27,  28,  27,  28,  28,  30,  37,  38,  38,  41,  43,  44,  44,
        45,  46,  45,  46,  46,  47,  47,  50,  52,  54,  57,  58,  59,
        60,  63,  65,  67,  68,  68,  70,  71,  72,  72,  73,  74,  76,
        77,  77,  82,  84,  85,  85,  86,  87,  88,  89,  88,  89,  89,
        93,  94,  99, 106, 108, 111, 112, 114, 118, 119, 119, 122, 123,
       123, 125, 128, 132, 134, 137, 144, 145, 146, 146, 147, 147, 148,
       149, 150, 149, 150, 150, 152, 153, 153, 154, 154, 156, 158, 159,
       159, 161, 171, 172, 172, 173, 174, 176, 178, 179, 181, 182, 183,
       183, 184, 184, 187, 189, 191, 192, 195, 197, 200, 202, 203, 204,
       205, 208, 211, 214, 217, 218, 219, 220, 220, 223, 226, 227, 228,
       231, 232, 234, 235, 236, 241, 242, 243, 243, 244, 244, 246, 248,
       249, 249, 251, 256, 257, 258, 260, 262, 264, 267, 268, 269, 270,
       273, 274, 274, 275, 282, 286, 290, 292, 293, 295, 301, 302, 302,
       306, 307, 311, 312, 312, 314, 316, 318, 322, 325, 328, 332, 335,
       342, 345, 346, 347, 349, 351, 353, 354, 354, 359, 360, 361, 361,
       362, 363, 364, 362, 363, 364, 363, 364, 364, 369, 370, 370, 373,
       374, 377, 380, 382, 385, 387, 395, 397, 399, 400, 400, 405, 406,
       406, 418, 420, 421, 421, 425, 426, 427, 429, 430, 430, 436, 439,
       443, 445, 446, 448, 449, 454, 455, 458, 459, 460, 459, 460, 460,
       462, 463, 463, 467, 468, 469, 470, 470, 475, 476, 476, 477, 477,
       478, 483, 484, 484, 487, 488, 488, 489, 489, 499, 502, 506, 508,
       509, 513, 517, 521, 524, 526, 527, 529, 532, 533, 533, 535, 538,
       540, 541, 541, 543, 545, 546, 546, 548, 549, 549, 552, 556, 558,
       559, 560, 561, 561, 563, 564, 565, 566, 567, 569, 571, 572, 572,
       573, 573, 575, 578, 581, 582, 582, 586, 587, 587, 589, 592, 598,
       601, 602, 602, 603, 603, 606, 608, 609, 609]))
Distances: [8.12344704e+00 2.00966701e+00 4.10340664e+01 3.92507888e+01
 1.58674248e+00 1.08844647e+01 1.49070369e+00 1.19575204e+01
 3.06998522e+00 1.01837260e+01 1.85343383e+00 5.00460133e+00
 1.44867283e+00 5.72107338e+00 1.65809571e+01 4.84863174e+00
 1.51430702e+01 1.39680161e+01 2.76516896e+00 1.18087975e+01
 7.49146814e+00 4.94018200e+00 1.78501921e+00 9.10782099e+00
 8.00535939e+00 3.56129315e+00 3.73293689e+00 2.34349831e+00
 3.84040212e-01 2.13051020e+00 2.47933365e+00 6.48928992e+00
 4.56785467e+00 3.06075108e+00 5.28769088e+00 4.59432131e+00
 9.23138767e+00 2.32140641e+00 2.34223337e+00 5.76885624e+00
 6.45978942e+00 1.52974148e+02 1.01581679e+00 6.09466975e-01
 1.16343081e+00 1.22479354e+00 3.09850402e+00 7.65863734e+00
 5.61859053e+00 7.88994792e+00 6.75234669e+00 1.18092905e+01
 3.02835735e+00 8.78095207e+00 3.38364477e+00 6.20677464e+00
 4.64006906e+00 2.09176898e+00 7.90297698e+00 4.27316829e+00
 1.16042614e+01 7.60972861e+00 9.97312974e+00 6.16175536e+00
 4.03225367e+00 4.70118099e+00 7.35889450e+00 5.63464314e+00
 3.73453914e+00 2.88189096e+00 2.82309468e+00 4.09755506e+00
 1.00189655e+01 2.80565877e+00 6.16244229e+00 7.18483249e+00
 4.12686363e+00 4.60178094e+00 3.02011445e+00 4.24679080e+00
 9.19091485e+00 3.82240595e+00 4.03150064e+00 3.68660443e+00
 7.03061772e+00 8.00371198e+01 7.12852563e+01 9.06081672e+00
 7.41517107e+00 9.53242202e+00 9.85778037e+00 8.75425906e+00
 1.03079026e+01 1.11616139e+01 1.34247485e+01 2.27263033e+00
 8.28258496e+00 1.63888465e+00 7.76949843e+00 2.45337510e+02
 2.52727262e+02 3.20125792e+00 2.53493761e+00 7.18951966e+00
 4.99426046e+00 4.26030148e+00 1.58388340e+00 2.91880169e+00
 1.37514237e+00 9.90933827e-01 1.94758369e+00 3.56693504e+00
 4.94300221e+00 9.72834128e+00 4.06042864e+00 1.07302634e+01
 5.81937731e+00 4.92240801e+00 2.55413050e+00 4.17135503e+00
 8.21828603e+00 1.93321088e+00 1.52889403e+01 1.22066027e+01
 2.16290027e+00 1.89237602e+00 1.27441206e+01 8.33164510e+00
 4.36746873e+00 1.62918473e+01 1.20571701e+00 1.22793098e-01
 9.77806759e+00 1.34631359e+01 8.50609711e+00 3.20950278e+00
 8.36285758e-01 7.72351551e+00 8.47902481e+00 7.69951099e+00
 1.76213298e+00 6.19156925e+00 3.45697383e+00 3.36835851e+00
 4.03848275e+00 1.48469513e+01 4.72048354e+00 9.22334206e-01
 7.36742302e+00 6.20641858e+00 5.60871267e+00 1.66499474e+00
 3.00093240e+00 2.33081133e+00 6.86959947e+00 3.29216216e+00
 1.08404060e+00 2.32836624e+00 2.51255957e+00 3.60121900e+00
 5.69659921e+00 6.01936558e+00 4.76398520e+00 2.65652959e+00
 2.01440313e+01 3.29056135e+01 3.56642278e+01 7.51634047e+01
 1.20662816e+02 8.61440664e-01 1.84969397e+00 2.70009487e+00
 4.06468370e+00 2.84851415e+00 1.02322055e+01 1.90346926e+00
 2.92506382e+00 1.48939700e+01 2.84008335e+00 9.90881030e+00
 3.89554753e+00 6.80698464e+00 2.75007323e+00 2.39103547e+00
 2.82391839e+00 2.57093876e+00 8.31293725e-01 1.04832941e+01
 7.31996302e+01 8.44371964e+00 6.51191759e+00 6.43940307e+00
 8.71555684e+00 2.84055260e+00 6.62857307e+00 5.18410137e+00
 4.03622873e+00 5.21775904e+00 9.96476910e-01 3.82413812e+00
 3.64646515e+00 2.71630442e+00 1.89807914e+00 3.65522560e+00
 1.20908700e+01 1.39502980e+02 1.58382092e+02 1.19684968e+02
 1.17345553e+02 1.22163738e+02 1.29996129e+02 1.76481480e+01
 1.51541206e+01 1.65408372e+01 5.61126349e+00 1.37683299e+01
 8.22714555e+00 5.02243583e+00 8.02998121e+00 3.50190942e+00
 2.63357323e+00 1.47966793e+01 4.76818908e+00 7.72336887e+00
 1.38572580e+00 3.76679983e+01 6.45762782e+01 8.99856734e+01
 5.55018838e+00 4.29360399e+00 1.89469444e+00 4.57154708e+00
 4.94158548e+00 1.02104369e+00 4.83089037e+00 2.07802416e+00
 4.90393130e+00 5.78278980e+00 1.26663263e+00 9.96976189e+00
 2.75245093e+00 2.08318559e+00 4.75978064e+00 5.55933120e+00
 2.99296013e+00 4.44136898e+00 7.54799755e+00 5.20497586e+00
 6.31899814e+00 4.07212870e+00 5.55246168e+00 1.35873845e+01
 6.88109843e+00 1.73478762e+00 1.86715924e+00 1.14585440e+00
 1.87383091e+00 7.84632227e-01 3.73871799e+00 2.99162110e+00
 1.08951354e+01 5.65489746e+00 7.65116153e+00 1.13020329e+01
 5.30261455e-02 6.88583918e-01 3.13585738e+00 2.44763181e+00
 3.64287197e+00 2.08944319e+00 5.28373546e+00 4.67717218e+00
 7.93296384e+00 4.22931738e+00 8.20938076e+00 4.11685448e+00
 4.09603076e+00 7.10289552e+00 7.56122752e+00 4.44597601e+00
 4.39000550e+00 4.26728388e+00 4.51839295e+00 3.27734617e+00
 1.04761811e+00 2.56510105e+00 1.24419186e+01 1.85635216e+01
 1.39545377e+01 1.98138324e+00 1.47776836e+01 2.50548648e+00
 3.58875201e+00 1.64300251e+01 4.49494665e+00 4.47400279e+01
 4.04232321e+01 7.75784830e+00 3.30115121e+00 3.21207919e+00
 1.95951490e+00 2.98141132e+00 6.34913761e+00 1.74755015e+00
 4.41599011e+00 4.20199569e+00 1.40980614e+01 7.51568763e+00
 6.89498530e+00 2.60182205e+00 2.17530982e+00 3.66931421e+00
 3.20600090e+00 6.74985558e+00 2.70338059e-01 6.55770662e+00
 5.79095855e+00 3.62177336e+00 5.10539063e+00 1.36841109e+01
 1.19016249e+01 2.81511714e+00 6.99136334e+00 8.33189977e+00
 1.24370877e+01 1.24325033e+01 1.23078912e+01 5.49945950e+00
 1.98728684e+02 4.65527089e+00 1.69342787e+00 3.24049290e+00
 2.84316851e+00 8.72061432e+00 1.14683888e+01 4.36704750e+00
 5.74754455e+00 5.11294833e+00 4.11108799e+00 1.66462648e+00
 5.77546621e+00 8.18632515e+00 2.62983340e+00 6.37270632e+00
 5.67282720e+00 7.24552848e+00 1.94873190e+00]
Filtered neighbor pairs (distance < 5): [False  True False False  True False  True False  True False  True False
  True False False  True False False  True False False  True  True False
 False  True  True  True  True  True  True False  True  True False  True
 False  True  True False False False  True  True  True  True  True False
 False False False False  True False  True False  True  True False  True
 False False False False  True  True False False  True  True  True  True
 False  True False False  True  True  True  True False  True  True  True
 False False False False False False False False False False False  True
 False  True False False False  True  True False  True  True  True  True
  True  True  True  True  True False  True False False  True  True  True
 False  True False False  True  True False False  True False  True  True
 False False False  True  True False False False  True False  True  True
  True False  True  True False False False  True  True  True False  True
  True  True  True  True False False  True  True False False False False
 False  True  True  True  True  True False  True  True False  True False
  True False  True  True  True  True  True False False False False False
 False  True False False  True False  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False  True  True False  True False  True False False False
 False  True  True  True  True  True  True  True  True False  True False
  True  True  True False  True  True False False False  True False False
 False  True  True  True  True  True  True  True False False False False
  True  True  True  True  True  True False  True False  True False  True
  True False False  True  True  True  True  True  True  True False False
 False  True False  True  True False  True False False False  True  True
  True  True False  True  True  True False False False  True  True  True
  True False  True False False  True False False False  True False False
 False False False False False  True  True  True  True False False  True
 False False  True  True False False  True False False False  True]
Time differences (seconds):
[[      0    4320    5040 ... 1192080 1194780 1196400]
 [   4320       0     720 ... 1187760 1190460 1192080]
 [   5040     720       0 ... 1187040 1189740 1191360]
 ...
 [1192080 1187760 1187040 ...       0    2700    4320]
 [1194780 1190460 1189740 ...    2700       0    1620]
 [1196400 1192080 1191360 ...    4320    1620       0]]
Time pairs (indices): (array([  2,   8,   8,   9,  16,  16,  16,  17,  17,  18,  20,  22,  25,
        25,  25,  26,  26,  27,  29,  36,  36,  37,  40,  42,  42,  43,
        43,  43,  44,  44,  45,  45,  46,  49,  51,  53,  56,  57,  58,
        59,  62,  64,  66,  66,  67,  69,  70,  70,  71,  72,  73,  75,
        75,  76,  81,  83,  83,  84,  85,  86,  86,  86,  87,  87,  88,
        92,  93,  98, 105, 107, 110, 111, 113, 117, 117, 118, 121, 121,
       122, 124, 127, 131, 133, 136, 143, 144, 144, 145, 145, 146, 147,
       147, 147, 148, 148, 149, 151, 151, 152, 152, 153, 155, 157, 157,
       158, 160, 170, 170, 171, 172, 173, 175, 177, 178, 180, 181, 181,
       182, 182, 183, 186, 188, 190, 191, 194, 196, 199, 201, 202, 203,
       204, 207, 210, 213, 216, 217, 218, 218, 219, 222, 225, 226, 227,
       230, 231, 233, 234, 235, 240, 241, 241, 242, 242, 243, 245, 247,
       247, 248, 250, 255, 256, 257, 259, 261, 263, 266, 267, 268, 269,
       272, 272, 273, 274, 281, 285, 289, 291, 292, 294, 300, 300, 301,
       305, 306, 310, 310, 311, 313, 315, 317, 321, 324, 327, 331, 334,
       341, 344, 345, 346, 348, 350, 352, 352, 353, 358, 359, 359, 360,
       360, 360, 360, 361, 361, 361, 362, 362, 363, 368, 368, 369, 372,
       373, 376, 379, 381, 384, 386, 394, 396, 398, 398, 399, 404, 404,
       405, 417, 419, 419, 420, 424, 425, 426, 428, 428, 429, 435, 438,
       442, 444, 445, 447, 448, 453, 454, 457, 457, 457, 458, 458, 459,
       461, 461, 462, 466, 467, 468, 468, 469, 474, 474, 475, 475, 476,
       477, 482, 482, 483, 486, 486, 487, 487, 488, 498, 501, 505, 507,
       508, 512, 516, 520, 523, 525, 526, 528, 531, 531, 532, 534, 537,
       539, 539, 540, 542, 544, 544, 545, 547, 547, 548, 551, 555, 557,
       558, 559, 559, 560, 562, 563, 564, 565, 566, 568, 570, 570, 571,
       571, 572, 574, 577, 580, 580, 581, 585, 585, 586, 588, 591, 597,
       600, 600, 601, 601, 602, 605, 607, 607, 608]), array([  3,   9,  10,  10,  17,  18,  19,  18,  19,  19,  21,  23,  26,
        27,  28,  27,  28,  28,  30,  37,  38,  38,  41,  43,  44,  44,
        45,  46,  45,  46,  46,  47,  47,  50,  52,  54,  57,  58,  59,
        60,  63,  65,  67,  68,  68,  70,  71,  72,  72,  73,  74,  76,
        77,  77,  82,  84,  85,  85,  86,  87,  88,  89,  88,  89,  89,
        93,  94,  99, 106, 108, 111, 112, 114, 118, 119, 119, 122, 123,
       123, 125, 128, 132, 134, 137, 144, 145, 146, 146, 147, 147, 148,
       149, 150, 149, 150, 150, 152, 153, 153, 154, 154, 156, 158, 159,
       159, 161, 171, 172, 172, 173, 174, 176, 178, 179, 181, 182, 183,
       183, 184, 184, 187, 189, 191, 192, 195, 197, 200, 202, 203, 204,
       205, 208, 211, 214, 217, 218, 219, 220, 220, 223, 226, 227, 228,
       231, 232, 234, 235, 236, 241, 242, 243, 243, 244, 244, 246, 248,
       249, 249, 251, 256, 257, 258, 260, 262, 264, 267, 268, 269, 270,
       273, 274, 274, 275, 282, 286, 290, 292, 293, 295, 301, 302, 302,
       306, 307, 311, 312, 312, 314, 316, 318, 322, 325, 328, 332, 335,
       342, 345, 346, 347, 349, 351, 353, 354, 354, 359, 360, 361, 361,
       362, 363, 364, 362, 363, 364, 363, 364, 364, 369, 370, 370, 373,
       374, 377, 380, 382, 385, 387, 395, 397, 399, 400, 400, 405, 406,
       406, 418, 420, 421, 421, 425, 426, 427, 429, 430, 430, 436, 439,
       443, 445, 446, 448, 449, 454, 455, 458, 459, 460, 459, 460, 460,
       462, 463, 463, 467, 468, 469, 470, 470, 475, 476, 476, 477, 477,
       478, 483, 484, 484, 487, 488, 488, 489, 489, 499, 502, 506, 508,
       509, 513, 517, 521, 524, 526, 527, 529, 532, 533, 533, 535, 538,
       540, 541, 541, 543, 545, 546, 546, 548, 549, 549, 552, 556, 558,
       559, 560, 561, 561, 563, 564, 565, 566, 567, 569, 571, 572, 572,
       573, 573, 575, 578, 581, 582, 582, 586, 587, 587, 589, 592, 598,
       601, 602, 602, 603, 603, 606, 608, 609, 609]))
Distances: [8.12344704e+00 2.00966701e+00 4.10340664e+01 3.92507888e+01
 1.58674248e+00 1.08844647e+01 1.49070369e+00 1.19575204e+01
 3.06998522e+00 1.01837260e+01 1.85343383e+00 5.00460133e+00
 1.44867283e+00 5.72107338e+00 1.65809571e+01 4.84863174e+00
 1.51430702e+01 1.39680161e+01 2.76516896e+00 1.18087975e+01
 7.49146814e+00 4.94018200e+00 1.78501921e+00 9.10782099e+00
 8.00535939e+00 3.56129315e+00 3.73293689e+00 2.34349831e+00
 3.84040212e-01 2.13051020e+00 2.47933365e+00 6.48928992e+00
 4.56785467e+00 3.06075108e+00 5.28769088e+00 4.59432131e+00
 9.23138767e+00 2.32140641e+00 2.34223337e+00 5.76885624e+00
 6.45978942e+00 1.52974148e+02 1.01581679e+00 6.09466975e-01
 1.16343081e+00 1.22479354e+00 3.09850402e+00 7.65863734e+00
 5.61859053e+00 7.88994792e+00 6.75234669e+00 1.18092905e+01
 3.02835735e+00 8.78095207e+00 3.38364477e+00 6.20677464e+00
 4.64006906e+00 2.09176898e+00 7.90297698e+00 4.27316829e+00
 1.16042614e+01 7.60972861e+00 9.97312974e+00 6.16175536e+00
 4.03225367e+00 4.70118099e+00 7.35889450e+00 5.63464314e+00
 3.73453914e+00 2.88189096e+00 2.82309468e+00 4.09755506e+00
 1.00189655e+01 2.80565877e+00 6.16244229e+00 7.18483249e+00
 4.12686363e+00 4.60178094e+00 3.02011445e+00 4.24679080e+00
 9.19091485e+00 3.82240595e+00 4.03150064e+00 3.68660443e+00
 7.03061772e+00 8.00371198e+01 7.12852563e+01 9.06081672e+00
 7.41517107e+00 9.53242202e+00 9.85778037e+00 8.75425906e+00
 1.03079026e+01 1.11616139e+01 1.34247485e+01 2.27263033e+00
 8.28258496e+00 1.63888465e+00 7.76949843e+00 2.45337510e+02
 2.52727262e+02 3.20125792e+00 2.53493761e+00 7.18951966e+00
 4.99426046e+00 4.26030148e+00 1.58388340e+00 2.91880169e+00
 1.37514237e+00 9.90933827e-01 1.94758369e+00 3.56693504e+00
 4.94300221e+00 9.72834128e+00 4.06042864e+00 1.07302634e+01
 5.81937731e+00 4.92240801e+00 2.55413050e+00 4.17135503e+00
 8.21828603e+00 1.93321088e+00 1.52889403e+01 1.22066027e+01
 2.16290027e+00 1.89237602e+00 1.27441206e+01 8.33164510e+00
 4.36746873e+00 1.62918473e+01 1.20571701e+00 1.22793098e-01
 9.77806759e+00 1.34631359e+01 8.50609711e+00 3.20950278e+00
 8.36285758e-01 7.72351551e+00 8.47902481e+00 7.69951099e+00
 1.76213298e+00 6.19156925e+00 3.45697383e+00 3.36835851e+00
 4.03848275e+00 1.48469513e+01 4.72048354e+00 9.22334206e-01
 7.36742302e+00 6.20641858e+00 5.60871267e+00 1.66499474e+00
 3.00093240e+00 2.33081133e+00 6.86959947e+00 3.29216216e+00
 1.08404060e+00 2.32836624e+00 2.51255957e+00 3.60121900e+00
 5.69659921e+00 6.01936558e+00 4.76398520e+00 2.65652959e+00
 2.01440313e+01 3.29056135e+01 3.56642278e+01 7.51634047e+01
 1.20662816e+02 8.61440664e-01 1.84969397e+00 2.70009487e+00
 4.06468370e+00 2.84851415e+00 1.02322055e+01 1.90346926e+00
 2.92506382e+00 1.48939700e+01 2.84008335e+00 9.90881030e+00
 3.89554753e+00 6.80698464e+00 2.75007323e+00 2.39103547e+00
 2.82391839e+00 2.57093876e+00 8.31293725e-01 1.04832941e+01
 7.31996302e+01 8.44371964e+00 6.51191759e+00 6.43940307e+00
 8.71555684e+00 2.84055260e+00 6.62857307e+00 5.18410137e+00
 4.03622873e+00 5.21775904e+00 9.96476910e-01 3.82413812e+00
 3.64646515e+00 2.71630442e+00 1.89807914e+00 3.65522560e+00
 1.20908700e+01 1.39502980e+02 1.58382092e+02 1.19684968e+02
 1.17345553e+02 1.22163738e+02 1.29996129e+02 1.76481480e+01
 1.51541206e+01 1.65408372e+01 5.61126349e+00 1.37683299e+01
 8.22714555e+00 5.02243583e+00 8.02998121e+00 3.50190942e+00
 2.63357323e+00 1.47966793e+01 4.76818908e+00 7.72336887e+00
 1.38572580e+00 3.76679983e+01 6.45762782e+01 8.99856734e+01
 5.55018838e+00 4.29360399e+00 1.89469444e+00 4.57154708e+00
 4.94158548e+00 1.02104369e+00 4.83089037e+00 2.07802416e+00
 4.90393130e+00 5.78278980e+00 1.26663263e+00 9.96976189e+00
 2.75245093e+00 2.08318559e+00 4.75978064e+00 5.55933120e+00
 2.99296013e+00 4.44136898e+00 7.54799755e+00 5.20497586e+00
 6.31899814e+00 4.07212870e+00 5.55246168e+00 1.35873845e+01
 6.88109843e+00 1.73478762e+00 1.86715924e+00 1.14585440e+00
 1.87383091e+00 7.84632227e-01 3.73871799e+00 2.99162110e+00
 1.08951354e+01 5.65489746e+00 7.65116153e+00 1.13020329e+01

            cluster  core
timestamp
1704098820       -5    -5
1704103140       -5    -5
1704103860       -5    -5
1704104100       -5    -5
1704105360       -5    -5
...             ...   ...
1705290780       -5    -5
1705290840       -5    -5
1705290900       -5    -5
1705293600       -5    -5
1705295220       -5    -5

[612 rows x 2 columns]

In [ ]:
neighbors = SD.find_neighbors(sample_user_df, time_thresh, dist_thresh, long_lat=False, datetime=False, traj_cols=traj_cols)

In [ ]:
dur_min = 100
dt_max = 120
delta_roam = 10

In [ ]:
SD.lachesis(sample_user_df, dur_min, dt_max, delta_roam, traj_cols=traj_cols, complete_output=False)